# Site settings
title: Swapnil Kathane
description: Portfolio of Swapnil
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Swapnil Kathane
user_description: Below mention are work domain for Freelancing. Till date, I work on the projects as mentioned below and lookimg forward for more such projects. 
                  If we talked about 3D Printing,I have one year exprience in 3D Printing specifically in FDM, SLS,SLA Technologies. I will provide 3D printing solution in most ompititive manner with best quality.
                  
user_title: Freelancer.
user_Contact: Phone
email: swapnilkathane106@outlook.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
